network:
    version: 2
    renderer: networkd
    ethernets:
        eth0:
            addresses:
                - 10.0.0.2/24
            nameservers:
                addresses: [8.8.8.8, 8.8.4.4]
            routes:
                - to: default
                  via: 10.0.0.1
